# Generated by Django 3.1.7 on 2021-03-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='data',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='foto',
            field=models.ImageField(null=True, upload_to='todo/'),
        ),
    ]
